---
Name: docs-routes
After: framework/routes#coreroutes
---
Director:
  rules:
    'en//QuickFeedbackForm': 'DocumentationViewer'
    'Security//$Action/$ID/$OtherID': 'Security'
    'admin': 'AdminRootController'
    'dev/buildcache/$Action': 'RebuildStaticCacheTask'
    'dev': 'DevelopmentAdmin'
    '': '->en/'
    '$Lang/$Version/$Action': 'DocumentationViewer'
